version: '3.8'

services:
  app:
    build: .
    container_name: pirates-form
    restart: unless-stopped
    ports:
      - 40000:8000
    env_file:
      - .env

  db:
    image: postgres:13.0-alpine
    container_name: pirates-form-postgres
    restart: unless-stopped
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $SQL_USER
      POSTGRES_PASSWORD: $SQL_PASSWORD
      POSTGRES_DB: $SQL_DATABASE
